sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t test_img -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true test_img npm test

after_success:
  - docker build -t dreampath88/mul-client ./client
  - docker build -t dreampath88/mul-nginx ./nginx
  - docker build -t dreampath88/mul-server ./server
  - docker build -t dreampath88/mul-worker ./worker