sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t test_img -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true test_img npm test

after_success:
  - docker build -t dreampath88/mul-client ./client
  - docker build -t dreampath88/mul-nginx ./nginx
  - docker build -t dreampath88/mul-server ./server
  - docker build -t dreampath88/mul-worker ./worker

  # Log in to the docker hub CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push them to docker hub
  - docker push dreampath88/mul-client 
  - docker push dreampath88/mul-nginx 
  - docker push dreampath88/mul-server 
  - docker push dreampath88/mul-worker 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-708213488323"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
