version: "3"
services:
  client:
    image: "dreampath88/mul-client"
    mem_limit: 128m
    hostname: client

  server:
    image: "dreampath88/mul-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      
  worker:
    image: "dreampath88/mul-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: "dreampath88/mul-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"

